In [3]:
import pandas as pd
from pandas import DataFrame, Series

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)
pd.set_option('display.width', 10000)

In [9]:
df = pd.read_csv("loanlist.csv", encoding="utf-8")
# df.set_index("ListingId", inplace=True)

In [10]:
new_frame = df[1:2]

In [11]:
new_frame

   ListingId   Amount CreditCode  Months  PayWay         PreAuditTime  Rate  RemainFunding            Title
1  125881425  12000.0          D      12       0  2018-08-23 09:39:47  30.0        10680.0  手机app用户的第1次闪电借款

In [14]:
new_frame[new_frame["ListingId"].isin(df["ListingId"])]

   ListingId   Amount CreditCode  Months  PayWay         PreAuditTime  Rate  RemainFunding            Title
1  125881425  12000.0          D      12       0  2018-08-23 09:39:47  30.0        10680.0  手机app用户的第1次闪电借款

In [19]:
    listing_ids = df["ListingId"].tolist()
    for x in range(0, len(listing_ids), 10):
        print(listing_ids[x: x+10])

[125881306, 125881425, 125882514, 125883448, 125883727, 125884190, 125884253, 125884529, 125884995, 125886185]
[125846597, 125888207, 125887696, 125887781, 125853712, 125889421, 125889486, 125889571, 125892666, 125893130]
[125894422, 125894965, 125895236, 125895344, 125895865, 125896772, 125897021, 125898915, 125899583, 125902844]
[125903214, 125903611, 125904008, 125904109, 125904519, 125906514, 125906816, 125910650, 125912838, 125913003]
[125913851, 125916561, 125920273, 125922198, 125922708, 125923659, 125929512, 125929762, 125929960, 125930193]
[125930982, 125932156, 125932526, 125929448, 125935703, 125935720, 125935956, 125853867, 125935796, 125935899]
[125935901, 125930193, 125932526, 125929448, 125935720, 125932978, 125933163, 125933203, 125936231, 125936237]
[125936267, 125936275, 125936287, 125936344, 125936345, 125936378, 125936379, 125936406, 125889421, 125889571]
[125903611, 125906816, 125912838, 125916561, 125922198, 125930193, 125932526, 125929448, 125935720, 125935956]
[125853867, 125936508, 125936653, 125936685]

In [138]:
df_listing_info = pd.read_csv("listingInfo.csv", encoding="utf-8")
print(df_listing_info.shape)
df_listing_info_D = df_listing_info[df_listing_info["CreditCode"] == "C"]
df_listing_info_D.tail()

(24360, 37)

       Age  Amount  AmountToReceive             AuditingTime     BorrowName  CancelCount  CertificateValidate CreditCode  CreditValidate  CurrentRate DeadLineTimeOrRemindTimeStr EducationDegree  FailedCount   FirstSuccessBorrowTime FistBidTime  Gender GraduateSchool  HighestDebt  HighestPrincipal LastBidTime    LastSuccessBorrowTime  LenderCount  ListingId  Months  NciicIdentityCheck  NormalCount  OverdueLessCount  OverdueMoreCount  OwingAmount  OwingPrincipal  PhoneValidate             RegisterTime  RemainFunding StudyStyle  SuccessCount  TotalPrincipal  WasteCount
23542   28  3540.0                0  2000-01-01T00:00:00.000  pdu0023853363            0                    0          C               0         24.0                   14天23时58分             NaN            0  2018-01-12T16:15:37.000         NaN       2            NaN      8837.94            6500.0         NaN  2018-07-31T18:44:42.000            0  126266979      12                   0           11                 0                 0      3772.70         3259.48              1  2018-01-12T16:08:54.000         3540.0        NaN             4         12277.0           1
23557   26  2356.0                0  2000-01-01T00:00:00.000  pdu3878385355            0                    0          C               0         24.0                   14天23时57分             NaN            0  2017-02-12T20:47:10.563         NaN       1            NaN      9791.82            6985.0         NaN  2018-05-02T01:31:50.000            0  126267023       6                   0           13                 0                 0      3394.80         2903.95              1  2017-02-11T18:59:41.000         2356.0        NaN             3         11285.0           3
23566   25  3068.0                0  2000-01-01T00:00:00.000  pdu7460551158            0                    0          C               0         24.0                   14天23时57分             NaN            0  2017-02-22T03:24:46.470         NaN       1            NaN     16694.16            7524.0         NaN  2018-08-03T15:11:07.000            0  126267064       6                   0           70                 0                 0     13418.41        12031.59              1  2017-02-21T23:52:54.000         3068.0        NaN            12         33824.0           0
23567   27  4102.0                0  2000-01-01T00:00:00.000  pdu2277212345            0                    0          C               0         24.0                   19天23时58分             NaN            0  2017-09-11T21:23:27.000         NaN       2            NaN     11487.58            6636.0         NaN  2018-06-28T14:57:36.000            0  126267084       6                   0           57                 0                 0      6396.87         5897.54              1  2017-09-11T19:48:10.000         4102.0        NaN            11         32403.0           0
23568   31  9017.0                0  2000-01-01T00:00:00.000  pdu4335834645            0                    1          C               0         24.0                   19天23时58分              本科            0  2016-03-23T12:41:25.510         NaN       1         天津商业大学     20252.05            9757.0         NaN  2018-06-29T17:01:57.000            0  126267085       6                   0          169                 1                 0     10022.41         9102.48              1  2016-03-23T12:00:43.000         9017.0         普通            42        102477.0           2

     Age  Amount  AmountToReceive             AuditingTime    ...     StudyStyle  SuccessCount  TotalPrincipal WasteCount
287   27  2000.0                0  2000-01-01T00:00:00.000    ...             普通             2          3400.0          0
288   24  1568.0                0  2000-01-01T00:00:00.000    ...            NaN             1          9500.0          0
289   20  2000.0                0  2000-01-01T00:00:00.000    ...            NaN             0             0.0          0
290   23  4550.0                0  2000-01-01T00:00:00.000    ...            NaN             0             0.0          2
291   24  3300.0                0  2000-01-01T00:00:00.000    ...            NaN             0             0.0          0

[5 rows x 37 columns]

In [26]:
df_listing_info.to_dict('records')

[{'Age': 47,
  'Amount': 2533.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'rong9496887',
  'CancelCount': 0,
  'CertificateValidate': 0,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '14天23时58分',
  'EducationDegree': nan,
  'FailedCount': 0,
  'FirstSuccessBorrowTime': '2017-04-09T18:13:34.000',
  'FistBidTime': nan,
  'Gender': 1,
  'GraduateSchool': nan,
  'HighestDebt': 9769.98,
  'HighestPrincipal': 6300.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': '2018-06-11T13:12:42.000',
  'LenderCount': 0,
  'ListingId': 126033464,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 43,
  'OverdueLessCount': 2,
  'OverdueMoreCount': 0,
  'OwingAmount': 6143.62,
  'OwingPrincipal': 5266.29,
  'PhoneValidate': 1,
  'RegisterTime': '2015-01-27T14:38:15.000',
  'RemainFunding': 2533.0,
  'StudyStyle': nan,
  'SuccessCount': 9,
  'TotalPrincipal': 18322.0,
  'WasteCount': 7},
 {'Age': 33,
  'Amount': 1000.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'pdu2854367909',
  'CancelCount': 0,
  'CertificateValidate': 1,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '14天23时53分',
  'EducationDegree': '专科',
  'FailedCount': 0,
  'FirstSuccessBorrowTime': '2018-06-13T14:19:13.000',
  'FistBidTime': nan,
  'Gender': 1,
  'GraduateSchool': '石家庄学院',
  'HighestDebt': 3834.78,
  'HighestPrincipal': 3250.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': '2018-06-13T14:19:13.000',
  'LenderCount': 0,
  'ListingId': 126032772,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 2,
  'OverdueLessCount': 0,
  'OverdueMoreCount': 0,
  'OwingAmount': 2556.52,
  'OwingPrincipal': 2182.81,
  'PhoneValidate': 1,
  'RegisterTime': '2018-06-13T14:13:01.000',
  'RemainFunding': 1000.0,
  'StudyStyle': '普通',
  'SuccessCount': 1,
  'TotalPrincipal': 3250.0,
  'WasteCount': 0},
 {'Age': 50,
  'Amount': 3500.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'pdu87065367',
  'CancelCount': 0,
  'CertificateValidate': 1,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '14天23时58分',
  'EducationDegree': '本科',
  'FailedCount': 0,
  'FirstSuccessBorrowTime': '2016-06-14T07:46:29.050',
  'FistBidTime': nan,
  'Gender': 1,
  'GraduateSchool': '上饶师范学院',
  'HighestDebt': 21067.4,
  'HighestPrincipal': 7000.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': '2018-07-28T15:49:01.000',
  'LenderCount': 0,
  'ListingId': 126033470,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 120,
  'OverdueLessCount': 7,
  'OverdueMoreCount': 0,
  'OwingAmount': 16808.55,
  'OwingPrincipal': 14426.8,
  'PhoneValidate': 1,
  'RegisterTime': '2015-03-12T16:47:51.000',
  'RemainFunding': 3500.0,
  'StudyStyle': '成人',
  'SuccessCount': 21,
  'TotalPrincipal': 71053.0,
  'WasteCount': 1},
 {'Age': 23,
  'Amount': 1487.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'pdu5206317157',
  'CancelCount': 2,
  'CertificateValidate': 0,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '14天23时53分',
  'EducationDegree': nan,
  'FailedCount': 0,
  'FirstSuccessBorrowTime': '2017-06-03T11:02:19.000',
  'FistBidTime': nan,
  'Gender': 1,
  'GraduateSchool': nan,
  'HighestDebt': 9480.79,
  'HighestPrincipal': 3500.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': '2018-07-15T10:33:37.000',
  'LenderCount': 0,
  'ListingId': 126032786,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 72,
  'OverdueLessCount': 1,
  'OverdueMoreCount': 0,
  'OwingAmount': 5168.13,
  'OwingPrincipal': 4612.84,
  'PhoneValidate': 1,
  'RegisterTime': '2016-09-22T18:05:39.000',
  'RemainFunding': 1487.0,
  'StudyStyle': nan,
  'SuccessCount': 17,
  'TotalPrincipal': 22716.0,
  'WasteCount': 1},
 {'Age': 30,
  'Amount': 2505.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'pdu7268714137',
  'CancelCount': 1,
  'CertificateValidate': 0,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '14天23时58分',
  'EducationDegree': nan,
  'FailedCount': 0,
  'FirstSuccessBorrowTime': '2016-10-28T18:42:46.720',
  'FistBidTime': nan,
  'Gender': 1,
  'GraduateSchool': nan,
  'HighestDebt': 4926.36,
  'HighestPrincipal': 4122.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': '2018-04-02T14:22:14.000',
  'LenderCount': 0,
  'ListingId': 126033471,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 23,
  'OverdueLessCount': 0,
  'OverdueMoreCount': 0,
  'OwingAmount': 1981.85,
  'OwingPrincipal': 1694.29,
  'PhoneValidate': 1,
  'RegisterTime': '2016-05-29T10:17:35.000',
  'RemainFunding': 2505.0,
  'StudyStyle': nan,
  'SuccessCount': 6,
  'TotalPrincipal': 11122.0,
  'WasteCount': 4},
 {'Age': 42,
  'Amount': 3800.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'pdu5402461773',
  'CancelCount': 0,
  'CertificateValidate': 0,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '14天23时40分',
  'EducationDegree': nan,
  'FailedCount': 0,
  'FirstSuccessBorrowTime': nan,
  'FistBidTime': nan,
  'Gender': 2,
  'GraduateSchool': nan,
  'HighestDebt': 0.0,
  'HighestPrincipal': 0.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': nan,
  'LenderCount': 0,
  'ListingId': 126031065,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 0,
  'OverdueLessCount': 0,
  'OverdueMoreCount': 0,
  'OwingAmount': 0.0,
  'OwingPrincipal': 0.0,
  'PhoneValidate': 1,
  'RegisterTime': '2017-12-02T08:45:35.000',
  'RemainFunding': 3800.0,
  'StudyStyle': nan,
  'SuccessCount': 0,
  'TotalPrincipal': 0.0,
  'WasteCount': 0},
 {'Age': 33,
  'Amount': 3800.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'pdu1718004157',
  'CancelCount': 0,
  'CertificateValidate': 0,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '14天23时40分',
  'EducationDegree': nan,
  'FailedCount': 0,
  'FirstSuccessBorrowTime': nan,
  'FistBidTime': nan,
  'Gender': 1,
  'GraduateSchool': nan,
  'HighestDebt': 0.0,
  'HighestPrincipal': 0.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': nan,
  'LenderCount': 0,
  'ListingId': 126031114,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 0,
  'OverdueLessCount': 0,
  'OverdueMoreCount': 0,
  'OwingAmount': 0.0,
  'OwingPrincipal': 0.0,
  'PhoneValidate': 1,
  'RegisterTime': '2016-08-05T12:25:23.000',
  'RemainFunding': 3800.0,
  'StudyStyle': nan,
  'SuccessCount': 0,
  'TotalPrincipal': 0.0,
  'WasteCount': 0},
 {'Age': 19,
  'Amount': 831.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'pdu6223214201',
  'CancelCount': 0,
  'CertificateValidate': 0,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '19天23时53分',
  'EducationDegree': nan,
  'FailedCount': 0,
  'FirstSuccessBorrowTime': '2017-04-14T10:42:18.000',
  'FistBidTime': nan,
  'Gender': 2,
  'GraduateSchool': nan,
  'HighestDebt': 2358.4,
  'HighestPrincipal': 2000.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': '2018-07-05T10:13:49.000',
  'LenderCount': 0,
  'ListingId': 126032796,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 29,
  'OverdueLessCount': 0,
  'OverdueMoreCount': 0,
  'OwingAmount': 1443.36,
  'OwingPrincipal': 1168.57,
  'PhoneValidate': 1,
  'RegisterTime': '2017-04-14T09:24:51.000',
  'RemainFunding': 831.0,
  'StudyStyle': nan,
  'SuccessCount': 6,
  'TotalPrincipal': 7318.0,
  'WasteCount': 0},
 {'Age': 43,
  'Amount': 2320.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'pdu7083234584',
  'CancelCount': 0,
  'CertificateValidate': 0,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '14天23时58分',
  'EducationDegree': nan,
  'FailedCount': 0,
  'FirstSuccessBorrowTime': '2018-03-06T17:44:14.000',
  'FistBidTime': nan,
  'Gender': 1,
  'GraduateSchool': nan,
  'HighestDebt': 6798.84,
  'HighestPrincipal': 5000.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': '2018-03-06T17:44:14.000',
  'LenderCount': 0,
  'ListingId': 126033475,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 5,
  'OverdueLessCount': 0,
  'OverdueMoreCount': 0,
  'OwingAmount': 3659.74,
  'OwingPrincipal': 2979.99,
  'PhoneValidate': 1,
  'RegisterTime': '2017-12-02T08:25:12.000',
  'RemainFunding': 2320.0,
  'StudyStyle': nan,
  'SuccessCount': 1,
  'TotalPrincipal': 5000.0,
  'WasteCount': 3},
 {'Age': 32,
  'Amount': 15400.0,
  'AmountToReceive': 0,
  'AuditingTime': '2000-01-01T00:00:00.000',
  'BorrowName': 'pdu6137534320',
  'CancelCount': 0,
  'CertificateValidate': 1,
  'CreditCode': 'AA',
  'CreditValidate': 0,
  'CurrentRate': 10.5,
  'DeadLineTimeOrRemindTimeStr': '14天23时53分',
  'EducationDegree': '本科',
  'FailedCount': 0,
  'FirstSuccessBorrowTime': '2016-09-21T21:29:20.997',
  'FistBidTime': nan,
  'Gender': 1,
  'GraduateSchool': '西南财经大学',
  'HighestDebt': 18542.46,
  'HighestPrincipal': 10000.0,
  'LastBidTime': nan,
  'LastSuccessBorrowTime': '2018-08-08T20:38:27.000',
  'LenderCount': 0,
  'ListingId': 126032803,
  'Months': 6,
  'NciicIdentityCheck': 0,
  'NormalCount': 55,
  'OverdueLessCount': 2,
  'OverdueMoreCount': 0,
  'OwingAmount': 0.0,
  'OwingPrincipal': 0.0,
  'PhoneValidate': 1,
  'RegisterTime': '2016-08-15T17:50:33.000',
  'RemainFunding': 15400.0,
  'StudyStyle': '网络教育',
  'SuccessCount': 8,
  'TotalPrincipal': 41072.0,
  'WasteCount': 1}]

In [2]:
key_dict = {"CreditCode": "级别",
            "Gender": "性别",
            "Months": "期限",
            "Age": "年龄",
            "OwingAmount": "待还金额"}

for key, value in key_dict.items():
    print(key, value)

CreditCode 级别
Gender 性别
Months 期限
Age 年龄
OwingAmount 待还金额

In [43]:
import pandas as pd
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 100000)
df_listinginfo = pd.read_csv("listingInfo.csv", encoding="utf-8")
df_loanlist = pd.read_csv("loanlist.csv", encoding="utf-8")


df = pd.merge(df_loanlist, df_listinginfo, on="ListingId",suffixes=['', '_y'])
df

       ListingId   Amount CreditCode  Months  PayWay         PreAuditTime  Rate  RemainFunding                    Title  Age  Amount_y  AmountToReceive             AuditingTime     BorrowName  CancelCount  CertificateValidate CreditCode_y  CreditValidate  CurrentRate DeadLineTimeOrRemindTimeStr EducationDegree  FailedCount   FirstSuccessBorrowTime              FistBidTime  Gender GraduateSchool  HighestDebt  HighestPrincipal              LastBidTime    LastSuccessBorrowTime  LenderCount  Months_y  NciicIdentityCheck  NormalCount  OverdueLessCount  OverdueMoreCount  OwingAmount  OwingPrincipal  PhoneValidate             RegisterTime  RemainFunding_y StudyStyle  SuccessCount  TotalPrincipal  WasteCount
0      126027538   8500.0          C      12       0  2018-08-24 15:40:51  24.0           93.0          手机app用户的第4次闪电借款   23    8500.0                0  2000-01-01T00:00:00.000  pdu1582636817            0                    0            C               0         24.0                   19天22时12分             NaN            0  2017-08-31T11:18:17.000  2018-08-24T15:40:53.000       1            NaN      9180.96            7700.0  2018-08-24T17:23:01.000  2018-06-27T04:28:36.000           89        12                   0            8                 0                 0      7526.41         6694.16              1  2016-08-04T05:30:19.000             93.0        NaN             3         15700.0           2
1      126028766  18948.0          C      12       0  2018-08-24 15:50:51  24.0         2002.0       pdu2****60348第6次借款   47   18948.0                0  2000-01-01T00:00:00.000  pdu2177860348            0                    0            C               0         24.0                   14天22时23分             NaN            0  2016-01-25T10:34:29.813  2018-08-24T15:50:53.000       1            NaN     15849.92           11213.0  2018-08-24T17:21:52.000  2018-01-13T11:21:12.000          209        12                   0           45                 0                 0      5410.60         5051.51              1  2016-01-11T11:40:04.000           2002.0        NaN             5         33040.0           2
2      126033891  10000.0          B      12       0  2018-08-24 16:28:20  20.0         5752.0       pdu5****30265第7次借款   39   10000.0                0  2000-01-01T00:00:00.000  pdu5086330265            0                    0            B               0         20.0                   14天23时56分             NaN            0  2016-07-20T12:45:14.730                      NaN       1            NaN     11877.96           10000.0                      NaN  2018-05-21T16:41:43.000            0        12                   0           47                16                 0      5586.66         5068.36              1  2016-06-17T10:17:17.000           9944.0        NaN             6         23001.0           0
3      126038921  33215.0          B      12       0  2018-08-24 17:11:13  20.0        27057.0       pdu3****14064第7次借款   37   33215.0                0  2000-01-01T00:00:00.000  pdu3881014064            1                    0            B               0         20.0                   14天23时44分             NaN            0  2017-06-12T18:23:49.000  2018-08-24T17:11:17.000       2            NaN     15486.63           10100.0  2018-08-24T17:22:51.000  2018-05-21T20:29:36.000           81        12                   0           31                 4                 0      7620.83         6784.78              1  2016-10-23T16:52:51.000          27057.0        NaN             6         35527.0           3
4      125937270    950.0         AA       6       0  2018-08-24 17:25:21  10.5          950.0  手机用户pdu5****47799的第1次借款   18     950.0                0  2000-01-01T00:00:00.000  pdu5506647799            0                    0           AA               0         10.5                   14天00时22分             NaN            0                      NaN                      NaN       2            NaN         0.00               0.0                      NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2018-08-23T17:41:09.000            950.0        NaN             0             0.0           0
5      126040161   1000.0         AA       6       0  2018-08-24 17:25:24  10.5         1000.0          手机app用户的第1次闪电借款   20    1000.0                0  2000-01-01T00:00:00.000  pdu7336772152            0                    0           AA               0         10.5                   19天23时54分             NaN            0                      NaN                      NaN       1            NaN         0.00               0.0                      NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2016-03-14T16:57:02.000           1000.0        NaN             0             0.0           2
6      126040218   7500.0         AA       6       0  2018-08-24 17:25:24  10.5         7500.0          手机app用户的第1次闪电借款   29    7500.0                0  2000-01-01T00:00:00.000  pdu6467136582            0                    0           AA               0         10.5                   19天23时54分             NaN            0                      NaN                      NaN       1            NaN         0.00               0.0                      NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2016-07-18T00:45:56.000           7500.0        NaN             0             0.0           0
7      126040219   4000.0         AA       6       0  2018-08-24 17:25:24  10.5         3900.0          手机app用户的第1次闪电借款   23    4000.0                0  2000-01-01T00:00:00.000  pdu1911178481            0                    0           AA               0         10.5                   19天23时54分             NaN            0                      NaN                      NaN       2            NaN         0.00               0.0                      NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2018-07-01T11:09:07.000           4000.0        NaN             0             0.0           0
8      126040294   6000.0         AA       6       0  2018-08-24 17:25:26  10.5         6000.0          手机app用户的第1次闪电借款   23    6000.0                0  2000-01-01T00:00:00.000  pdu3550516350            0                    0           AA               0         10.5                   19天23时55分             NaN            0                      NaN                      NaN       1            NaN         0.00               0.0                      NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2017-05-11T11:32:51.000           6000.0        NaN             0             0.0           1
9      126040323   1600.0         AA       6       0  2018-08-24 17:25:27  10.5         1600.0         手机app用户的第23次闪电借款   25    1600.0                0  2000-01-01T00:00:00.000  pdu7814582500            0                    0           AA               0         10.5                   19天23时55分             NaN            0  2016-10-10T12:17:23.570                      NaN       2            NaN      5134.63            3990.0                      NaN  2018-07-22T13:01:10.000            0         6                   0          116                 3                 0      3242.35         2883.82              1  2016-10-08T12:03:56.000           1600.0        NaN            22         24842.0           1
10     126040325   2443.0         AA       6       0  2018-08-24 17:25:27  10.5         2443.0               手机app用户的借款   25    2443.0                0  2000-01-01T00:00:00.000  pdu2328072281            0                    0           AA               0         10.5                   14天23时55分             NaN            0  2018-04-10T11:36:28.000                      NaN       1            NaN      2719.32            2000.0                      NaN  2018-04-10T11:36:28.000            0         6                   0            4                 0                 0      1812.88         1356.44              1  2017-02-20T23:42:52.000           2443.0        NaN             1          2000.0           0
11     126040327   5200.0         AA       6       0  2018-08-24 17:25:28  10.5         5200.0       pdu5****57016第3次借款   27    5200.0                0  2000-01-01T00:00:00.000  pdu5257357016            0                    0           AA               0         10.5                   14天23时55分             NaN            0  2017-06-04T16:17:11.000                      NaN       1            NaN      4666.98            4000.0                      NaN  2017-11-07T14:22:50.000            0         6                   0            6                 0                 0         0.00            0.00              1  2017-06-04T16:04:42.000           5200.0        NaN             3          8000.0           0
12     126040338   1000.0         AA       6       0  2018-08-24 17:25:30  10.5         1000.0          手机app用户的第3次闪电借款   33    1000.0                0  2000-01-01T00:00:00.000  pdu2725788806            0                    0           AA               0         10.5                   19天23时55分             NaN            0  2018-03-15T12:31:39.000                      NaN       1            NaN      8158.68            6000.0                      NaN  2018-06-21T08:50:59.000            0         6                   0            7                 0                 0      5290.81         4255.76              1  2018-01-10T19:33:55.000           1000.0        NaN             2          7000.0           0
13     126040346   6700.0          C       6       0  2018-08-24 17:25:30  24.0         6700.0       pdu7****60701第3次借款   25    6700.0                0  2000-01-01T00:00:00.000  pdu7440460701            1                    0            C               0         24.0                   14天23时55分             NaN            0  2017-10-23T20:29:06.000                      NaN       1            NaN      7079.16            6000.0                      NaN  2018-08-14T14:56:13.000            0         6                   0            7                 0                 0         0.00            0.00              1  2017-10-23T19:51:17.000           6700.0        NaN             2         10500.0           1
14     126040351   1034.0          B      12       0  2018-08-24 17:25:30  20.0         1034.0               手机app用户的借款   21    1034.0                0  2000-01-01T00:00:00.000  pdu4804676656            0                    0            B               0         20.0                   14天23时55分             NaN            0  2017-07-15T11:34:59.000                      NaN       1            NaN      6269.06            2200.0                      NaN  2018-07-26T10:38:14.000            0        12                   0           38                 0                 0      5120.01         4365.92              1  2017-07-05T21:34:58.000           1034.0        NaN            16         17448.0           0
15     126040359   1305.0         AA       6       0  2018-08-24 17:25:31  10.5         1305.0               手机app用户的借款   36    1305.0                0  2000-01-01T00:00:00.000  pdu1441059574            1                    0           AA               0         10.5                   14天23时55分             NaN            0  2018-05-25T15:22:29.000                      NaN       1            NaN      7079.76            6000.0                      NaN  2018-07-10T23:43:53.000            0         6                   0            4                 0                 0      5388.58         4734.37              1  2018-05-25T14:51:59.000           1305.0        NaN             2          8003.0           0
16     126040363    800.0         AA       6       0  2018-08-24 17:25:31  10.5          800.0          手机app用户的第8次闪电借款   21     800.0                0  2000-01-01T00:00:00.000    pdu48411407            0                    0           AA               0         10.5                   19天23时55分             NaN            0  2017-02-22T12:07:13.427                      NaN       1            NaN      2346.52            2000.0                      NaN  2018-06-29T13:06:04.000            0         6                   0           34                 9                 0      1270.48         1102.18              1  2015-04-30T00:09:13.000            800.0        NaN             8          8074.0           0
17     126040365   1664.0         AA       6       0  2018-08-24 17:25:32  10.5         1664.0       pdu3****73454第2次借款   50    1664.0                0  2000-01-01T00:00:00.000  pdu3215873454            1                    0           AA               0         10.5                   14天23时55分             NaN            0  2018-02-05T15:42:47.000                      NaN       1            NaN      4079.04            3000.0                      NaN  2018-02-05T15:42:47.000            0         6                   0            3                 3                 0      1957.02         1535.44              1  2018-02-02T19:53:18.000           1664.0        NaN             1          3000.0           0
18     126040370    700.0         AA       6       0  2018-08-24 17:25:32  10.5          700.0               手机app用户的借款   20     700.0                0  2000-01-01T00:00:00.000  pdu3833447583            1                    0           AA               0         10.5                   14天23时56分             NaN            0  2017-08-24T21:00:27.000                      NaN       1            NaN      5827.55            2391.0                      NaN  2018-08-19T03:07:18.000            0         6                   0           20                16                 0      3229.14         2720.81              1  2017-06-20T18:11:32.000            700.0        NaN            11         11620.0           3
19     126040372   2998.0         AA       6       0  2018-08-24 17:25:32  10.5         2998.0               手机app用户的借款   27    2998.0                0  2000-01-01T00:00:00.000  pdu8265031199            0                    0           AA               0         10.5                   14天23时56分             NaN            0  2018-06-20T14:04:33.000                      NaN       1            NaN     22282.18           18800.0                      NaN  2018-06-20T14:04:33.000            0         6                   0            1                 1                 0     18154.16        15801.55              1  2018-06-20T14:01:26.000           2998.0        NaN             1         18800.0           0
20     126040384   4000.0         AA       6       0  2018-08-24 17:25:34  10.5         4000.0               手机app用户的借款   26    4000.0                0  2000-01-01T00:00:00.000  pdu5135205283            1                    0           AA               0         10.5                   14天23时56分             NaN            0  2018-05-07T13:33:36.000                      NaN       1            NaN      2745.03            2000.0                      NaN  2018-05-07T13:33:36.000            0         6                   0            2                 1                 0      1874.34         1521.24              1  2018-03-19T12:02:01.000           4000.0        NaN             1          2000.0           5
21     126040392  12000.0          A      12       0  2018-08-24 17:25:35  16.0        12000.0               手机app用户的借款   26   12000.0                0  2000-01-01T00:00:00.000  pdu1141232854            0                    1            A               0         16.0                   14天23时56分              本科            0  2017-06-24T11:44:05.000                      NaN       1     重庆大学城市科技学院     18546.37           11000.0                      NaN  2018-02-13T19:21:26.000            0        12                   0           18                 0                 0      6369.36         5879.96              1  2017-06-24T11:38:11.000          12000.0         普通             2         22000.0           0
22     126040398    633.0         AA       6       0  2018-08-24 17:25:35  10.5          633.0          手机app用户的第4次闪电借款   21     633.0                0  2000-01-01T00:00:00.000  pdu1210747412            0                    0           AA               0         10.5                   19天23时56分             NaN            0  2016-12-11T21:34:18.820                      NaN       1            NaN      1459.44            1150.0                      NaN  2018-06-26T21:54:07.000            0         6                   0           14                 0                 0       583.09          516.10              1  2016-11-23T19:48:48.000            633.0        NaN             3          2400.0           4
23     126040402   1285.0         AA       6       0  2018-08-24 17:25:35  10.5         1285.0          手机app用户的第3次闪电借款   36    1285.0                0  2000-01-01T00:00:00.000  pdu2846577037            1                    0           AA               0         10.5                   19天23时56分             NaN            0  2018-05-03T17:34:42.000                      NaN       2            NaN     16161.69            7455.0                      NaN  2018-06-19T13:26:58.000            0         6                   0            4                 0                 0     14220.87        11214.89              1  2018-03-27T22:22:13.000           1285.0        NaN             2         13455.0           1
24     126040429   4200.0         AA       6       0  2018-08-24 17:25:37  10.5         4150.0          手机app用户的第1次闪电借款   31    4200.0                0  2000-01-01T00:00:00.000  pdu1144217208            0                    0           AA               0         10.5                   19天23时56分             NaN            0                      NaN                      NaN       1            NaN         0.00               0.0                      NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2016-01-21T21:51:27.000           4200.0        NaN             0             0.0           2
25     126040431   2751.0         AA       6       0  2018-08-24 17:25:37  10.5         2751.0               手机app用户的借款   22    2751.0                0  2000-01-01T00:00:00.000    pdu57015226            0                    0           AA               0         10.5                   14天23时56分             NaN            0  2016-08-30T14:12:35.420                      NaN       2            NaN     24396.06           10500.0                      NaN  2018-07-16T13:46:23.000            0         6                   0           80                 0                 0     21041.78        18648.93              1  2015-10-25T08:09:42.000           2751.0        NaN            13         60111.0           0
26     126040432    500.0         AA       6       0  2018-08-24 17:25:38  10.5          500.0          手机app用户的第5次闪电借款   19     500.0                0  2000-01-01T00:00:00.000  pdu6267050328            0                    0           AA               0         10.5                   19天23时56分             NaN            0  2018-03-13T18:30:04.000                      NaN       1            NaN       679.80             500.0                      NaN  2018-06-23T18:51:03.000            0         6                   0           23                 0                 0         0.00            0.00              1  2017-05-08T22:34:13.000            500.0        NaN             4          2000.0           4

In [63]:
def show_column_info(df):
    for column_name in ["CreditCode", "Months", "Rate", "StudyStyle"]:
        print()
        print(df[column_name].value_counts())

In [76]:
df_credit_code = df[(df["CreditCode"] == "AA")]
show_column_info(df_credit_code)
df_credit_code

AA    15258
Name: CreditCode, dtype: int64

6     15161
24       97
Name: Months, dtype: int64

10.5    15157
12.0       97
9.0         4
Name: Rate, dtype: int64

普通       1496
成人        588
网络教育      133
自考         71
*          28
开放教育       26
普通全日制      16
研究生        12
自学考试       10
业余          6
函授          3
不详          3
脱产          3
Name: StudyStyle, dtype: int64

       ListingId  Amount CreditCode  Months  PayWay         PreAuditTime  Rate  RemainFunding                    Title  Age  Amount_y  AmountToReceive             AuditingTime     BorrowName  CancelCount  CertificateValidate CreditCode_y  CreditValidate  CurrentRate DeadLineTimeOrRemindTimeStr EducationDegree  FailedCount   FirstSuccessBorrowTime FistBidTime  Gender GraduateSchool  HighestDebt  HighestPrincipal LastBidTime    LastSuccessBorrowTime  LenderCount  Months_y  NciicIdentityCheck  NormalCount  OverdueLessCount  OverdueMoreCount  OwingAmount  OwingPrincipal  PhoneValidate             RegisterTime  RemainFunding_y StudyStyle  SuccessCount  TotalPrincipal  WasteCount
4      125937270   950.0         AA       6       0  2018-08-24 17:25:21  10.5          950.0  手机用户pdu5****47799的第1次借款   18     950.0                0  2000-01-01T00:00:00.000  pdu5506647799            0                    0           AA               0         10.5                   14天00时22分             NaN            0                      NaN         NaN       2            NaN         0.00               0.0         NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2018-08-23T17:41:09.000            950.0        NaN             0             0.0           0
5      126040161  1000.0         AA       6       0  2018-08-24 17:25:24  10.5         1000.0          手机app用户的第1次闪电借款   20    1000.0                0  2000-01-01T00:00:00.000  pdu7336772152            0                    0           AA               0         10.5                   19天23时54分             NaN            0                      NaN         NaN       1            NaN         0.00               0.0         NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2016-03-14T16:57:02.000           1000.0        NaN             0             0.0           2
6      126040218  7500.0         AA       6       0  2018-08-24 17:25:24  10.5         7500.0          手机app用户的第1次闪电借款   29    7500.0                0  2000-01-01T00:00:00.000  pdu6467136582            0                    0           AA               0         10.5                   19天23时54分             NaN            0                      NaN         NaN       1            NaN         0.00               0.0         NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2016-07-18T00:45:56.000           7500.0        NaN             0             0.0           0
7      126040219  4000.0         AA       6       0  2018-08-24 17:25:24  10.5         3900.0          手机app用户的第1次闪电借款   23    4000.0                0  2000-01-01T00:00:00.000  pdu1911178481            0                    0           AA               0         10.5                   19天23时54分             NaN            0                      NaN         NaN       2            NaN         0.00               0.0         NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2018-07-01T11:09:07.000           4000.0        NaN             0             0.0           0
8      126040294  6000.0         AA       6       0  2018-08-24 17:25:26  10.5         6000.0          手机app用户的第1次闪电借款   23    6000.0                0  2000-01-01T00:00:00.000  pdu3550516350            0                    0           AA               0         10.5                   19天23时55分             NaN            0                      NaN         NaN       1            NaN         0.00               0.0         NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2017-05-11T11:32:51.000           6000.0        NaN             0             0.0           1
9      126040323  1600.0         AA       6       0  2018-08-24 17:25:27  10.5         1600.0         手机app用户的第23次闪电借款   25    1600.0                0  2000-01-01T00:00:00.000  pdu7814582500            0                    0           AA               0         10.5                   19天23时55分             NaN            0  2016-10-10T12:17:23.570         NaN       2            NaN      5134.63            3990.0         NaN  2018-07-22T13:01:10.000            0         6                   0          116                 3                 0      3242.35         2883.82              1  2016-10-08T12:03:56.000           1600.0        NaN            22         24842.0           1
10     126040325  2443.0         AA       6       0  2018-08-24 17:25:27  10.5         2443.0               手机app用户的借款   25    2443.0                0  2000-01-01T00:00:00.000  pdu2328072281            0                    0           AA               0         10.5                   14天23时55分             NaN            0  2018-04-10T11:36:28.000         NaN       1            NaN      2719.32            2000.0         NaN  2018-04-10T11:36:28.000            0         6                   0            4                 0                 0      1812.88         1356.44              1  2017-02-20T23:42:52.000           2443.0        NaN             1          2000.0           0
11     126040327  5200.0         AA       6       0  2018-08-24 17:25:28  10.5         5200.0       pdu5****57016第3次借款   27    5200.0                0  2000-01-01T00:00:00.000  pdu5257357016            0                    0           AA               0         10.5                   14天23时55分             NaN            0  2017-06-04T16:17:11.000         NaN       1            NaN      4666.98            4000.0         NaN  2017-11-07T14:22:50.000            0         6                   0            6                 0                 0         0.00            0.00              1  2017-06-04T16:04:42.000           5200.0        NaN             3          8000.0           0
12     126040338  1000.0         AA       6       0  2018-08-24 17:25:30  10.5         1000.0          手机app用户的第3次闪电借款   33    1000.0                0  2000-01-01T00:00:00.000  pdu2725788806            0                    0           AA               0         10.5                   19天23时55分             NaN            0  2018-03-15T12:31:39.000         NaN       1            NaN      8158.68            6000.0         NaN  2018-06-21T08:50:59.000            0         6                   0            7                 0                 0      5290.81         4255.76              1  2018-01-10T19:33:55.000           1000.0        NaN             2          7000.0           0
15     126040359  1305.0         AA       6       0  2018-08-24 17:25:31  10.5         1305.0               手机app用户的借款   36    1305.0                0  2000-01-01T00:00:00.000  pdu1441059574            1                    0           AA               0         10.5                   14天23时55分             NaN            0  2018-05-25T15:22:29.000         NaN       1            NaN      7079.76            6000.0         NaN  2018-07-10T23:43:53.000            0         6                   0            4                 0                 0      5388.58         4734.37              1  2018-05-25T14:51:59.000           1305.0        NaN             2          8003.0           0
16     126040363   800.0         AA       6       0  2018-08-24 17:25:31  10.5          800.0          手机app用户的第8次闪电借款   21     800.0                0  2000-01-01T00:00:00.000    pdu48411407            0                    0           AA               0         10.5                   19天23时55分             NaN            0  2017-02-22T12:07:13.427         NaN       1            NaN      2346.52            2000.0         NaN  2018-06-29T13:06:04.000            0         6                   0           34                 9                 0      1270.48         1102.18              1  2015-04-30T00:09:13.000            800.0        NaN             8          8074.0           0
17     126040365  1664.0         AA       6       0  2018-08-24 17:25:32  10.5         1664.0       pdu3****73454第2次借款   50    1664.0                0  2000-01-01T00:00:00.000  pdu3215873454            1                    0           AA               0         10.5                   14天23时55分             NaN            0  2018-02-05T15:42:47.000         NaN       1            NaN      4079.04            3000.0         NaN  2018-02-05T15:42:47.000            0         6                   0            3                 3                 0      1957.02         1535.44              1  2018-02-02T19:53:18.000           1664.0        NaN             1          3000.0           0
18     126040370   700.0         AA       6       0  2018-08-24 17:25:32  10.5          700.0               手机app用户的借款   20     700.0                0  2000-01-01T00:00:00.000  pdu3833447583            1                    0           AA               0         10.5                   14天23时56分             NaN            0  2017-08-24T21:00:27.000         NaN       1            NaN      5827.55            2391.0         NaN  2018-08-19T03:07:18.000            0         6                   0           20                16                 0      3229.14         2720.81              1  2017-06-20T18:11:32.000            700.0        NaN            11         11620.0           3
19     126040372  2998.0         AA       6       0  2018-08-24 17:25:32  10.5         2998.0               手机app用户的借款   27    2998.0                0  2000-01-01T00:00:00.000  pdu8265031199            0                    0           AA               0         10.5                   14天23时56分             NaN            0  2018-06-20T14:04:33.000         NaN       1            NaN     22282.18           18800.0         NaN  2018-06-20T14:04:33.000            0         6                   0            1                 1                 0     18154.16        15801.55              1  2018-06-20T14:01:26.000           2998.0        NaN             1         18800.0           0
20     126040384  4000.0         AA       6       0  2018-08-24 17:25:34  10.5         4000.0               手机app用户的借款   26    4000.0                0  2000-01-01T00:00:00.000  pdu5135205283            1                    0           AA               0         10.5                   14天23时56分             NaN            0  2018-05-07T13:33:36.000         NaN       1            NaN      2745.03            2000.0         NaN  2018-05-07T13:33:36.000            0         6                   0            2                 1                 0      1874.34         1521.24              1  2018-03-19T12:02:01.000           4000.0        NaN             1          2000.0           5
22     126040398   633.0         AA       6       0  2018-08-24 17:25:35  10.5          633.0          手机app用户的第4次闪电借款   21     633.0                0  2000-01-01T00:00:00.000  pdu1210747412            0                    0           AA               0         10.5                   19天23时56分             NaN            0  2016-12-11T21:34:18.820         NaN       1            NaN      1459.44            1150.0         NaN  2018-06-26T21:54:07.000            0         6                   0           14                 0                 0       583.09          516.10              1  2016-11-23T19:48:48.000            633.0        NaN             3          2400.0           4
23     126040402  1285.0         AA       6       0  2018-08-24 17:25:35  10.5         1285.0          手机app用户的第3次闪电借款   36    1285.0                0  2000-01-01T00:00:00.000  pdu2846577037            1                    0           AA               0         10.5                   19天23时56分             NaN            0  2018-05-03T17:34:42.000         NaN       2            NaN     16161.69            7455.0         NaN  2018-06-19T13:26:58.000            0         6                   0            4                 0                 0     14220.87        11214.89              1  2018-03-27T22:22:13.000           1285.0        NaN             2         13455.0           1
24     126040429  4200.0         AA       6       0  2018-08-24 17:25:37  10.5         4150.0          手机app用户的第1次闪电借款   31    4200.0                0  2000-01-01T00:00:00.000  pdu1144217208            0                    0           AA               0         10.5                   19天23时56分             NaN            0                      NaN         NaN       1            NaN         0.00               0.0         NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2016-01-21T21:51:27.000           4200.0        NaN             0             0.0           2
25     126040431  2751.0         AA       6       0  2018-08-24 17:25:37  10.5         2751.0               手机app用户的借款   22    2751.0                0  2000-01-01T00:00:00.000    pdu57015226            0                    0           AA               0         10.5                   14天23时56分             NaN            0  2016-08-30T14:12:35.420         NaN       2            NaN     24396.06           10500.0         NaN  2018-07-16T13:46:23.000            0         6                   0           80                 0                 0     21041.78        18648.93              1  2015-10-25T08:09:42.000           2751.0        NaN            13         60111.0           0
26     126040432   500.0         AA       6       0  2018-08-24 17:25:38  10.5          500.0          手机app用户的第5次闪电借款   19     500.0                0  2000-01-01T00:00:00.000  pdu6267050328            0                    0           AA               0         10.5                   19天23时56分             NaN            0  2018-03-13T18:30:04.000         NaN       1            NaN       679.80             500.0         NaN  2018-06-23T18:51:03.000            0         6                   0           23                 0                 0         0.00            0.00              1  2017-05-08T22:34:13.000            500.0        NaN             4          2000.0           4
28     126040442   884.0         AA       6       0  2018-08-24 17:25:39  10.5          884.0       pdu1****65535第3次借款   19     884.0                0  2000-01-01T00:00:00.000  pdu1727765535            0                    0           AA               0         10.5                   14天23时56分             NaN            0  2018-06-05T09:19:41.000         NaN       2            NaN      5883.87            3000.0         NaN  2018-06-24T13:11:38.000            0         6                   0            6                 0                 0      4617.09         3615.53              1  2018-03-08T16:22:19.000            884.0        NaN             2          4976.0           1
29     126040452  5000.0         AA       6       0  2018-08-24 17:25:41  10.5         5000.0          手机app用户的第1次闪电借款   32    5000.0                0  2000-01-01T00:00:00.000    pdu70266638            0                    0           AA               0         10.5                   19天23时56分             NaN            0                      NaN         NaN       1            NaN         0.00               0.0         NaN                      NaN            0         6                   0            0                 0                 0         0.00            0.00              1  2015-09-08T13:27:16.000           5000.0        NaN             0             0.0           1
30     126040445  4654.0         AA       6       0  2018-08-24 17:25:41  10.5         4654.0                g***第9次借款   35    4654.0                0  2000-01-01T00:00:00.000           gylj            0                    0           AA               0         10.5                   14天23时56分             NaN            0  2015-11-07T00:47:29.583         NaN       1            NaN      9196.55            4900.0         NaN  2018-06-25T20:01:33.000            0         6                   0           20                24                 4      1506.41         1345.45              1  2014-09-09T15:45:28.000           4654.0        NaN             8         23400.0           3
31     126040446   700.0         AA       6       0  2018-08-24 17:25:41  10.5          700.0          手机app用户的第2次闪电借款   37     700.0                0  2000-01-01T00:00:00.000  pdu1130384525            1                    0           AA               0         10.5                   19天23时56分             NaN            0  2018-05-02T12:53:07.000         NaN       1            NaN      3399.81            2500.0         NaN  2018-05-02T12:53:07.000            0         6                   0            3                 0                 0      2491.92         1900.41              1  2016-12-09T22:37:34.000            700.0        NaN             1          2500.0           2
32     126040456   606.0         AA       6       0  2018-08-24 17:25:41  10.5          606.0          手机app用户的第2次闪电借款   20     606.0                0  2000-01-01T00:00:00.000  pdu7582812717            0                    0           AA               0         10.5                   19天23时56分             NaN            0  2018-03-16T15:26:00.000         NaN       2            NaN      2039.64            1500.0         NaN  2018-03-16T15:26:00.000            0         6                   0            5                 0                 0      1163.54          894.00              1  2016-11-26T19:11:15.000            606.0        NaN             1          1500.0           8
33     126040462  4000.0         AA       6       0  2018-08-24 17:25:42  10.5         4000.0          手机app用户的第8次闪电借款   28    4000.0                0  2000-01-01T00:00:00.000  pdu6457744266            0                    1           AA               0         10.5                   19天23时56分              专科            0  2017-05-15T15:35:20.000         NaN       1           西昌学院     10889.76            8500.0         NaN  2018-06-08T12:12:48.000            0         6                   0           44                15                 0      1506.41         1345.45              1  2017-05-15T15:22:07.000           4000.0         普通            16         23260.0          10
34     126040465  2998.0         AA       6       0  2018-08-24 17:25:42  10.5         2998.0               手机app用户的借款   23    2998.0                0  2000-01-01T00:00:00.000  pdu2858264471            1                    0           AA               0         10.5                   14天23时56分             NaN            0  2017-11-06T10:02:48.000         NaN       2            NaN      6294.69            5000.0         NaN  2018-06-23T15:33:36.000            0         6                   0           33                 2                 0      2956.66         2722.04              1  2015-12-22T17:36:16.000           2998.0        NaN             8         13179.0           0
35     126040475  1600.0         AA       6       0  2018-08-24 17:25:44  10.5         1600.0         手机app用户的第25次闪电借款   22    1600.0                0  2000-01-01T00:00:00.000  pdu1257720784            0                    1           AA               0         10.5                   19天23时56分              专科            0  2017-06-11T19:38:33.000         NaN       2         国家开放大学      8627.46            3500.0         NaN  2018-08-19T20:25:16.000            0         6                   0          101                 4                 0      6732.62         6151.83              1  2017-06-11T19:22:21.000           1600.0       开放教育            24         31968.0           0

In [25]:
from collections import deque

cache = deque(df["ListingId"], 10)

cache.append(1000000)

In [26]:
cache

deque([126062950,
       126062945,
       126062953,
       126062959,
       126062962,
       126062964,
       126062966,
       126062977,
       126062978,
       1000000])

In [21]:
d2 = deque([126062978, 126062979])

In [24]:
%timeit list(set(d2).difference(cache))

944 ns ± 12.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [28]:
cache.extend(d2)

In [29]:
cache

deque([126062953,
       126062959,
       126062962,
       126062964,
       126062966,
       126062977,
       126062978,
       1000000,
       126062978,
       126062979])

In [77]:
for x in range(0, 10, 2):
    print(x)

0
2
4
6
8

In [81]:
url = "//invest.ppdai.com/loan/info?id=118892468&debtdealid=118670569"
url.find("&debt")

41

In [84]:
url_new = url[:url.find("&debtdealid")]

In [83]:
url_new

'//invest.ppdai.com/loan/info?id=118892468'

In [85]:
key = "其他事项\n\n\n\n                                包括但不限于借款人财务状况、还款能力变化、涉诉情况、受行政处罚情况等"

In [87]:
key.find("asdf")

-1

In [135]:

df_debt_info = pd.read_csv("DebtInfo.csv", encoding="utf-8")
display(df_debt_info.shape)
display(df_debt_info[df_debt_info.Days > 30])

(16149, 22)

       AllowanceRadio              BidDateTime CreditCode CurrentCreditCode  Days     DebtId          Lender  ListingAmount  ListingId  ListingMonths  ListingRate              ListingTime  OwingInterest  OwingNumber  OwingPrincipal  PastDueDay  PastDueNumber  PreferenceDegree  PriceforSale  PriceforSaleRate          Seller  StatusId
8                0.95  2018-07-30T18:46:42.290          B                 G    34  118732837   pdu4724384648         2260.0  123337973             12         20.0  2018-07-30T18:37:29.220           4.73           11           46.21           0              0             56.46         45.67              22.0   pdu4724384648         1
9                0.65  2018-04-04T09:43:59.690          B                 G    38  118732838   pdu4724384648         7777.0  106141832             12         22.0  2018-04-04T09:07:43.180           2.27            7           30.49           2              3              8.62         30.15              24.0   pdu4724384648         1
12               0.00  2018-04-27T13:02:19.403          B                 G    31  118733047  qyg13851146221        11700.0  109757627             12         22.0  2018-04-27T12:55:19.583           2.91            8           34.53           1              1             50.97         34.53              22.0  qyg13851146221         1
74               0.00  2018-04-11T15:13:10.207          B                 E    75  118955440   pdu3535150185         7000.0  107364419             12         22.0  2018-04-11T15:11:05.947           1.71            6           26.37           1              1             -3.26         25.69              22.0   pdu3535150185         1
140              0.00  2017-11-28T15:22:52.717          B                 B    31  118956069   pdu5764275186        17770.0   86363049             12         18.0  2017-11-28T14:16:29.310           0.40            3           13.35           1              1            -20.15         13.34              18.0   pdu5764275186         1
145              0.00  2017-11-29T00:42:17.817          B                 B    32  118956081   pdu1516561045         6192.0   86480543             12         18.0  2017-11-29T00:41:44.640           0.80            3           26.70           0              0             -8.88         26.68              18.0   pdu5764275186         1
155              0.00  2017-11-29T09:58:53.560          B                 C    32  118956096   pdu5665531312         4027.0   86518695             12         18.0  2017-11-29T09:57:14.213           0.40            3           13.35           0              0             -3.34         13.34              18.0   pdu5764275186         1
156              0.00  2017-11-28T07:37:30.777          B                 B    31  118956098   pdu5764275186        21501.0   86268464             12         18.0  2017-11-28T01:54:48.200           0.40            3           13.35           1              1            -20.15         13.34              18.0   pdu5764275186         1
169              0.00  2018-02-28T22:37:39.467          B                 F    31  118956118   pdu3535150185         2500.0  101018432             12         22.0  2018-02-28T22:36:20.830           1.71            6           26.37           1              1             10.13         26.36              22.0   pdu3535150185         1
205              0.00  2018-01-28T14:24:07.963          B                 F    31  118956518   pdu5764275186         8000.0   96564371             12         18.0  2018-01-28T14:23:19.543           0.99            5           21.93           0              0             26.75         21.92              18.0   pdu5764275186         1
206              0.00  2018-02-01T03:38:28.690          B                 F    34  118956519   pdu5764275186         3900.0   97179577             12         18.0  2018-02-01T03:37:31.480           1.60            5           35.08           0              0             38.24         35.03              18.0   pdu5764275186         1
209              0.00  2018-01-28T01:19:25.430          B                 E    31  118956534   pdu5764275186         5000.0   96490527             12         18.0  2018-01-28T01:18:01.420           0.99            5           21.93           0              0             26.75         21.92              18.0   pdu5764275186         1
212              0.00  2018-01-28T21:06:14.247          B                 C    31  118956538   pdu5764275186        13000.0   96623663             12         18.0  2018-01-28T20:58:12.750           0.99            5           21.93           0              0             -9.67         21.92              18.0   pdu5764275186         1
213              0.00  2018-01-28T10:35:16.547          B                 E    31  118956540   pdu5764275186         5600.0   96526435             12         18.0  2018-01-28T10:34:30.900           0.99            5           21.93           0              0             26.86         21.92              18.0   pdu5764275186         1
214              0.00  2018-01-28T10:09:36.563          B                 C    31  118956541   pdu5764275186         5000.0   96522689             12         18.0  2018-01-28T10:08:19.290           0.99            5           21.93           0              0            -15.42         21.92              18.0   pdu5764275186         1
237              0.00  2018-05-30T17:17:06.383          B                 F    35  118931898   pdu5682443042         7283.0  113956608             12         22.0  2018-05-24T19:14:09.380           3.61            9           38.51           4              1              6.36         38.41              22.0   pdu5682443042         1
247              0.00  2018-07-12T17:26:41.170          B                 F    45  118931909   pdu5227663553         2000.0  121128767             12         20.0  2018-07-12T17:20:56.450           3.97           10           42.34           1              1             59.60         42.01              20.0   pdu5227663553         1
281              0.00  2018-06-28T15:06:09.550          B                 F    31  118961671   pdu8561732681         6807.0  119092476             12         20.0  2018-06-28T09:52:56.987           3.98           10           42.34           0              0            162.79         42.34              20.0   pdu8561732681         1
282              0.00  2018-06-28T15:06:47.137          B                 F    31  118961672   pdu8561732681         2000.0  117150615             12         20.0  2018-06-16T11:39:02.483           3.98           10           42.34           0              0              9.90         42.34              20.0   pdu8561732681         1
283              0.00  2018-06-28T15:06:16.747          B                 G    31  118961673   pdu8561732681         4127.0  116819694             12         20.0  2018-06-13T16:35:17.097           3.98           10           42.34           0              0            134.30         42.34              20.0   pdu8561732681         1
284              0.00  2018-06-28T15:06:53.753          B                 G    31  118961674   pdu8561732681         1700.0  117636536             12         20.0  2018-06-20T13:19:58.410           3.96           10           42.35           0              0             33.96         42.33              20.0   pdu8561732681         1
285              0.00  2018-06-28T15:06:03.923          B                 F    31  118961675   pdu8561732681         3476.0  117759435             12         20.0  2018-06-21T11:42:33.900           3.97           10           42.35           0              0            157.80         42.34              20.0   pdu8561732681         1
286              0.00  2018-04-28T07:02:46.250          B                 E    31  118960199  qyg13851146221        10724.0  109849995             12         22.0  2018-04-27T23:29:40.140           2.91            8           34.53          11              2             88.73         34.53              22.0  qyg13851146221         1
566              0.00  2018-05-31T21:48:41.683          B                 B    33  118957324   pdu5764275186         3484.0  115010004              6         20.0  2018-05-31T21:46:41.750           7.64            3          228.53           0              0            -12.15        228.26              20.0   pdu5764275186         1
567              0.00  2018-06-12T11:00:00.553          B                 C    45  118957331   pdu5764275186         2000.0  116654928              6         20.0  2018-06-12T10:57:10.883           7.66            3          229.56           0              0             -9.31        227.81              20.0   pdu5764275186         1
568              0.00  2018-08-03T01:36:20.967          B                 A    36  118957568   pdu5764275186        25000.0  123717949              3         20.0  2018-08-03T01:33:30.943           8.08            2          322.64           0              0             -8.55        321.77              20.0   pdu5764275186         1
569              0.00  2018-08-01T16:25:23.117          B                 A    34  118957573   pdu5764275186         6000.0  123552822              3         20.0  2018-08-01T16:21:06.783           8.06            2          321.97           0              0             -7.99        321.44              20.0   pdu5764275186         1
570              0.00  2018-07-29T17:46:14.903          B                 A    32  118957574   pdu5764275186         8262.0  123230838              3         20.0  2018-07-29T17:43:38.000           8.04            2          321.30           0              0            -16.72        321.11              20.0   pdu5764275186         1
586              0.00  2018-06-16T11:06:58.383          B                 B    49  118957317   pdu5764275186         1040.0  117146307              6         20.0  2018-06-16T11:05:00.693           5.08            3          151.67           0              0            -13.87        150.21              20.0   pdu5764275186         1
587              0.00  2018-06-01T08:15:17.350          B                 B    34  118957332   pdu5764275186         3000.0  115044849              6         20.0  2018-06-01T08:12:28.790           7.63            3          228.53           0              0             -9.67        228.13              20.0   pdu5764275186         1
...               ...                      ...        ...               ...   ...        ...             ...            ...        ...            ...          ...                      ...            ...          ...             ...         ...            ...               ...           ...               ...             ...       ...
15197            0.16  2018-04-05T10:33:59.347          B                 F    38  118706407   pdu1621336535         2300.0  106317254             12         22.0  2018-04-05T10:30:46.880           4.54            7           60.97           1              1              0.85         60.57              22.5   pdu1621336535         1
15199            0.16  2018-03-28T15:38:42.340          B                 G    31  118706409   pdu1621336535         4045.0  105045844             12         22.0  2018-03-28T15:36:21.430           2.27            7           30.49           1              1             12.67         30.41              22.5   pdu1621336535         1
15229            0.95  2018-03-28T15:59:47.283          B                 G    31  118706066   pdu1621336535         3705.0  105049316             12         22.0  2018-03-28T15:57:06.977           2.27            7           30.49           1              2              4.68         30.17              25.0   pdu1621336535         1
15251            0.00  2018-06-28T15:07:29.063          B                 E    32  118705521   pdu8561732681         5000.0  118850649             12         20.0  2018-06-26T14:10:27.693           3.98           10           42.34           0              0             69.17         42.29              20.0   pdu8561732681         1
15312            0.00  2018-06-29T02:32:57.227          B                 F    32  118704825     blue_skyfly        12000.0  119193802             12         20.0  2018-06-29T02:31:29.717           3.98           10           42.34           1              1             60.20         42.29              20.0     blue_skyfly         1
15316            0.00  2018-06-28T18:24:28.050          B                 E    31  118704995     zhaolei0914        12000.0  119158248             12         20.0  2018-06-28T18:20:38.117           3.98           10           42.34           0              0             15.23         42.31              20.0     zhaolei0914         1
15337            0.00  2018-01-31T12:11:12.080          B                 G    33  118705256   pdu7731724662         3800.0   97052905             12         22.0  2018-01-31T12:09:17.480           1.23            5           22.17          11              1            316.81         22.12              22.0   pdu3717320361         1
15441            0.00  2018-06-04T12:45:22.287          B                 D    37  118703818   pdu1146058838         3700.0  115532754             12         20.0  2018-06-04T12:33:33.430          16.35            9          192.07           1              2             -4.90        191.34              20.0   pdu1146058838         1
15490            0.00  2018-05-19T19:45:19.613          B                 E    52  118703334     pdu88072202         8816.0  113214724             12         22.0  2018-05-19T19:42:36.193           5.82            8           69.06           0              0             -5.73         68.17              22.0     pdu88072202         1
15549            0.00  2018-07-04T15:08:43.380          B                 E    37  118701832   pdu0584878256         2800.0  119973551             12         20.0  2018-07-04T14:28:56.050           3.98           10           42.34           0              0              8.22         42.18              20.0   pdu0584878256         1
15589            0.00  2018-04-28T14:53:47.603          B                 E    31  118700781   pdu2132654763        15800.0  109938796             12         22.0  2018-04-28T14:50:45.260           8.96            8          106.35           0              0            -11.34        106.28              22.0   pdu2132654763         1
15600            0.00  2018-04-29T17:16:31.890          B                 G    32  118700309   pdu5086132288         2100.0  110104628             12         22.0  2018-04-29T17:14:13.653           3.49            8           41.44          19              1             33.70         41.38              22.0   pdu5086132288         1
15618            0.00  2018-04-11T15:13:08.740          B                 E    75  118700624   pdu8655346232         7000.0  107364419             12         22.0  2018-04-11T15:11:05.947           1.71            6           26.37           1              1             -3.73         25.67              22.0   pdu8655346232         1
15707            0.00  2018-02-20T23:50:57.153          B                 E    53  118698928     pdu88072202         3263.0   99899120             12         22.0  2018-02-20T23:50:37.787           1.23            5           22.17           1              1             -8.23         21.86              22.0     pdu88072202         1
15716            0.00  2018-05-06T09:18:52.720          B                 G    39  118699963     pdu88072202        12035.0  111102242             12         22.0  2018-05-06T09:16:22.877           2.91            8           34.53           0              0             26.84         34.34              22.0     pdu88072202         1
15745            0.00  2018-05-08T12:08:16.373          B                 G    41  118699490     pdu88072202        14000.0  111445110             12         22.0  2018-05-08T12:05:29.733           2.91            8           34.53           6              3             38.30         34.30              22.0     pdu88072202         1
15746            0.00  2018-05-08T13:58:44.427          B                 G    41  118699491     pdu88072202         4000.0  111461201             12         22.0  2018-05-08T13:56:21.497           2.92            8           34.53           0              0             19.11         34.31              22.0     pdu88072202         1
15751            0.00  2018-05-18T17:02:03.083          B                 G    51  118698371   pdu0315315112         2000.0  113056124             12         22.0  2018-05-18T16:58:05.130           2.91            8           34.53           1              1             84.62         34.10              22.0   pdu0315315112         1
15905            0.00  2018-02-28T09:26:51.290          B                 G    31  118697475     pdu81276557        11000.0  100866176             12         22.0  2018-02-28T09:25:25.637           2.05            6           31.64           2              2             14.27         31.61              22.0   pdu7405634251         1
15906            0.00  2018-04-18T20:23:22.070          B                 E    51  118697476   pdu2161671464         5067.0  108460111             12         22.0  2018-04-18T20:21:49.523           2.27            7           30.49           1              1             -0.37         30.11              22.0   pdu7405634251         1
15907            0.00  2018-06-08T11:33:30.787          B                 G    41  118697479   pdu7384428746         2200.0  116131976             12         20.0  2018-06-08T11:30:20.990          32.67            9          384.14           0              0             43.39        381.85              20.0   pdu7405634251         1
15908            0.00  2018-02-01T17:24:04.683          B                 F    34  118697481     pdu06037646         5000.0   97293253             12         22.0  2018-02-01T17:22:24.487           1.23            5           22.17           3              2             45.71         22.11              22.0   pdu7405634251         1
15909            0.00  2018-03-05T14:06:31.207          B                 G    38  118697482   pdu5721325308         5173.0  101664897             12         22.0  2018-03-05T13:47:47.087           8.65            6          132.86           1              2             87.00        132.23              22.0   pdu7405634251         1
15910            0.00  2018-03-05T14:06:31.510          B                 G    38  118697483   pdu1614123555         5173.0  101664897             12         22.0  2018-03-05T13:47:47.087           8.58            6          131.81           1              2             86.96        131.18              22.0   pdu7405634251         1
15944            0.00  2018-06-07T12:52:30.930          B                 E    40  118697433   pdu4841378062         2500.0  115989731             12         20.0  2018-06-07T11:46:49.203           3.26            9           38.42           0              0            -15.47         38.20              20.0   pdu4841378062         1
15957            0.00  2018-05-20T14:41:58.407          B                 G    53  118697097   pdu5504235377         1000.0  113316231             12         22.0  2018-05-20T14:39:01.377           2.91            8           34.53           1              1             35.14         34.06              22.0   pdu5504235377         1
15985            0.00  2018-05-28T14:50:56.320          B                 E    31  118696888   pdu6184325700         6573.0  114490568             12         22.0  2018-05-28T14:48:27.660           3.61            9           38.51           0              0              4.34         38.48              22.0   pdu6184325700         1

In [162]:
df_debt_all_info = pd.merge(df_debt_info, df_listing_info, on="ListingId", suffixes=('', '_y'))
df_debt_all_info_over30 = df_debt_all_info[df_debt_all_info.Days > 60]

In [163]:
def show_column_info(df):
    for column_name in ["CreditCode", "Months", "CurrentCreditCode", "ListingRate", "PastDueDay", "PastDueNumber", "Age", "CertificateValidate",
                      "CreditValidate", "EducationDegree", "Gender", "OverdueLessCount", "OverdueMoreCount", "StudyStyle"]:
        print()
        print(df[column_name].value_counts())

In [164]:
show_column_info(df_debt_all_info_over30)

B    8
Name: CreditCode, dtype: int64

12    7
6     1
Name: Months, dtype: int64

E    3
F    2
C    2
D    1
Name: CurrentCreditCode, dtype: int64

20.0    5
22.0    3
Name: ListingRate, dtype: int64

0    5
1    3
Name: PastDueDay, dtype: int64

0    5
1    3
Name: PastDueNumber, dtype: int64

27    2
24    2
23    1
29    1
28    1
33    1
Name: Age, dtype: int64

1    6
0    2
Name: CertificateValidate, dtype: int64

0    5
1    3
Name: CreditValidate, dtype: int64

专科    4
本科    2
Name: EducationDegree, dtype: int64

2    5
1    3
Name: Gender, dtype: int64

0     5
3     2
15    1
Name: OverdueLessCount, dtype: int64

0    8
Name: OverdueMoreCount, dtype: int64

成人    3
普通    3
Name: StudyStyle, dtype: int64